### PR TITLE
fix(settings): DNS cache UI consistency, validation, and conditional rendering

### LINKED ISSUE #2385: DNS cache fields styling and validation is broken
### Description

A bug fix for this already exists. This issue is created simply to trigger our duplicate workflow and to test it.

The real issues was dns cache fields styling and validation was broken.

### Version

develop

### Steps to Reproduce

1. Go to settings > network
2. Turn on dns cache

### Screenshots

Image

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

-

### Operating System

-

### Browser

-

### Additional Context

_No response_

### Search Existing Issues

- [x] Yes, I have searched existing issues.

### Code of Conduct

- [x] I agree to follow Seerr's Code of Conduct

### PR DESCRIPTION
**Pull request by fallenbagel**
## Description
Fix DNS cache TTL input styling to match app standards and fix the yup validation to allow -1 as a valid max TTL (default value). Also hides DNS cache stats when caching is disabled.

- Fixes #2385

## How Has This Been Tested?
- Tested the validation on the settings -> network -> DNS cache fields
- Went to settings -> jobs&cache -> observed dns cache stats were hidden when it wasnt enabled

### Field stylings:
image

### DNS cache disabled:
image

### No DNS Cache entries:
image

### DNS Cached entries:
image

## Checklist:

- [x] I have read and followed the contribution [guidelines](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md).
- [ ] Disclosed any use of AI (see our [policy](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md#ai-assistance-notice))
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] Successful build `pnpm build`
- [x] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

### CODE REVIEW

File: src/components/Settings/SettingsNetwork/index.tsx [hunk 1]
```diff
@@ -288,50 +288,50 @@ const SettingsNetwork = () => {
...
+                            className="short"
+                          />
                         </div>
+                        {errors.dnsCacheForceMinTtl &&
+                          touched.dnsCacheForceMinTtl &&
+                          typeof errors.dnsCacheForceMinTtl === 'string' && (
+                            <div className="error">
+                              {errors.dnsCacheForceMinTtl}
+                            </div>
+                          )}
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply src/components/Settings/SettingsNetwork/index.tsx:315]: Dumbest.

File: src/components/Settings/SettingsNetwork/index.tsx [hunk 2]
```diff
@@ -288,50 +288,50 @@ const SettingsNetwork = () => {
...
+                            className="short"
+                          />
                         </div>
+                        {errors.dnsCacheForceMaxTtl &&
+                          touched.dnsCacheForceMaxTtl &&
+                          typeof errors.dnsCacheForceMaxTtl === 'string' && (
+                            <div className="error">
+                              {errors.dnsCacheForceMaxTtl}
+                            </div>
+                          )}
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply src/components/Settings/SettingsNetwork/index.tsx:339]: Dumbest.

File: src/i18n/locale/en.json [hunk 3]
```diff
@@ -890,6 +890,7 @@
   "components.Settings.SettingsJobsCache.dnsCacheDescription": "Seerr caches DNS lookups to optimize performance and avoid making unnecessary API calls.",
   "components.Settings.SettingsJobsCache.dnsCacheGlobalStats": "Global DNS Cache Stats",
   "components.Settings.SettingsJobsCache.dnsCacheGlobalStatsDescription": "These stats are aggregated across all DNS cache entries.",
+  "components.Settings.SettingsJobsCache.dnsNoCacheEntries": "No DNS lookups have been cached yet.",
   "components.Settings.SettingsJobsCache.dnscacheactiveaddress": "Active Address",
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply src/i18n/locale/en.json:894]: Stupid.

File: src/i18n/locale/en.json [hunk 4]
```diff
@@ -1015,6 +1016,7 @@
   "components.Settings.SettingsNetwork.proxyBypassFilterTip": "Use ',' as a separator, and '*.' as a wildcard for subdomains",
   "components.Settings.SettingsNetwork.proxyBypassLocalAddresses": "Bypass Proxy for Local Addresses",
   "components.Settings.SettingsNetwork.proxyEnabled": "HTTP(S) Proxy",
+  "components.Settings.SettingsNetwork.proxyEnabledTip": "Send ALL outgoing HTTP/HTTPS requests through a proxy server (host/port). Does NOT enable HTTPS, SSL, or certificate configuration.",
   "components.Settings.SettingsNetwork.proxyHostname": "Proxy Hostname",
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply src/i18n/locale/en.json:1020]: So stupid

File: server/interfaces/api/settingsInterfaces.ts [hunk 5]
```diff
@@ -48,6 +48,7 @@ export interface PublicSettingsResponse {
   emailEnabled: boolean;
   newPlexLogin: boolean;
   youtubeUrl: string;
+  dnsCacheEnabled: boolean;
```
Comment (gauthier-th) [inline server/interfaces/api/settingsInterfaces.ts]: I don't understand why this has to be included in the public settings?

Comment (fallenbagel) [reply server/interfaces/api/settingsInterfaces.ts]: Because we are accessing:
```
      {settings.currentSettings.dnsCacheEnabled && (
```
the currentSettings is a public setting response. Without it, it will cause a type error as that wont be present

Comment (fallenbagel) [reply server/interfaces/api/settingsInterfaces.ts]: https://github.com/seerr-team/seerr/blob/develop/src%2Fcontext%2FSettingsContext.tsx#L7

Comment (gauthier-th) [reply server/interfaces/api/settingsInterfaces.ts]: Yes, but this information is only used in the network settings page? It's not used anywhere else. We could just fetch this information when accessing the network info page, without exposing it globally just for that page.

Comment (fallenbagel) [reply server/interfaces/api/settingsInterfaces.ts]: > Yes, but this information is only used in the network settings page? It's not used anywhere else. We could just fetch this information when accessing the network info page, without exposing it globally just for that page.

But doesnt this adds an extra request for data? doing a network request. Another thing we could do is:
derive it from cacheData itself since the /api/v1/settings/cache response already includes dnsCache. And server only returns that data if dns caching is enabled. Is that better?

Comment (fallenbagel) [reply server/interfaces/api/settingsInterfaces.ts]: I have decided to derive it from dnsCache. Should be better since we wont need to make another request then

Comment (gauthier-th) [reply server/interfaces/api/settingsInterfaces.ts]: Yes, better this way.

File: src/components/Settings/SettingsNetwork/index.tsx [hunk 6]
```diff
@@ -29,6 +29,8 @@ const messages = defineMessages('components.Settings.SettingsNetwork', {
   trustProxyTip:
     'Allow Seerr to correctly register client IP addresses behind a proxy',
   proxyEnabled: 'HTTP(S) Proxy',
+  proxyEnabledTip:
+    'Send ALL outgoing HTTP/HTTPS requests through a proxy server (host/port). Does NOT enable HTTPS, SSL, or certificate configuration.',
```
Comment (0xSysR3ll) [inline src/components/Settings/SettingsNetwork/index.tsx:33]: Typo ? (host:port)

Comment (fallenbagel) [reply src/components/Settings/SettingsNetwork/index.tsx:33]: Nope I meant it like your proxy server (with the host/port)

**Review by 0xSysR3ll — APPROVED** [review]
