### PR TITLE
fix(smtp-notification-test): missing allowSelfSigned option in test function

### LINKED ISSUE #1374: Unable to send email to server with Self-signed certificate
### Description

Similar to this issue https://github.com/Fallenbagel/jellyseerr/issues/187, I'm unable to send emails with the "Allow self-signed certificate" option enabled, but the server has been conrrectly used by other applications on my network like nextcloud and voultwarden.

To make things worse, the debug logs are not very verbose, which makes it a bit difficult to get to the level of detail we need.

EDIT: Good news, the issue seems to affect only the test functionality, not the actual notifications

### Version

 2.3.0

### Steps to Reproduce

1. Go to Settings > Notifications > Email
2. Type the SMTP Server data, port 587, STARTTLS if available
3. Mark Allow Self-Signed Certificates 
4. Save and send Test Email

### Screenshots

_No response_

### Logs

```shell
{"recipient":"[xxxx]","type":"TEST_NOTIFICATION","subject":"Test Notification","errorMessage":"self-signed certificate"}
```

### Platform

desktop

### Database

SQLite (default)

### Device

Mac

### Operating System

MacOS 15.3.1 (24D70)

### Browser

Chrome

### Additional Context

_No response_

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by 0xSysR3ll**
#### Description

The SMTP test functionality was not working when using self-signed certificates due to the missing `allowSelfSigned` option in the request body.

This commit ensures that `allowSelfSigned: values.allowSelfSigned` is properly included, allowing self-signed certificates when enabled in the settings.

#### To-Dos

- [x] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #1374

### CODE REVIEW

File: src/components/Settings/Notifications/NotificationsEmail.tsx [hunk 1]
```diff
@@ -133,10 +133,10 @@ const NotificationsEmail = () => {
...
           ? 'implicit'
           : data.options.requireTls
-          ? 'opportunistic'
-          : data.options.ignoreTls
-          ? 'none'
-          : 'default',
+            ? 'opportunistic'
+            : data.options.ignoreTls
+              ? 'none'
+              : 'default',
```
Comment (gauthier-th) [inline src/components/Settings/Notifications/NotificationsEmail.tsx]: Please remove these changes.

**Review by gauthier-th — CHANGES_REQUESTED** [review]

File: src/components/Settings/Notifications/NotificationsEmail.tsx (hunk 1 above)
Comment (0xSysR3ll) [reply src/components/Settings/Notifications/NotificationsEmail.tsx]: Hello, sorry my prettier extension messed this up !

**Review by fallenbagel — APPROVED** [review]

**Review by gauthier-th — APPROVED** [review]
