### PR TITLE
fix: improve local login UX

### LINKED ISSUE #1108: Popup to enter Email Address
### Description

I use exclusively the Jellyfin accounts, so when people login using that they have no Email associated to their account. 

In my experience people love getting personal direct notifications about the things they do on my Jellyseerr instance, but explaining to every single person in a 1 to 1 conversation that they can get that, they just need to go to "Settings" and enter an email address, is annoying.
This behavior is just to implicit and hidden for normal users to find and understand it from my experience.

### Desired Behavior

I would like to have an option for users who log in to get a popup for entering their Email address, maybe just the first time they do. 

Mainly I want the system to educate people about the notification via Email option and let them enter the only missing info (email address) right then and there. 
A "That sounds nice, sure here is my email" is all it should take. Or alternatively "No thanks" and then a little bit of text mentioning where the user can add the email later if they change their mind.

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by fallenbagel**
## Description

This PR addresses several UX pain points around local login, particularly for Jellyfin/Emby instances where usernames are used in place of email addresses.

The local login form placeholder has been changed from "Email Address / Username" to just "Email Address", with a contextual hint shown for Jellyfin/Emby instances explaining that users without an email set can use their username.

The password settings page now clarifies that the password is for local login and is separate from the media server password.

Admins are now warned when importing users that imported accounts don't have a local password set, and a warning is shown on the user settings page when disabling media server sign-in, since this could lock out users who haven't set a local password.

The local login error message now distinguishes between invalid credentials and actual server errors instead of showing a generic "Something went wrong" for both.

The email required warning has been moved from the bottom of the sidebar (where it was easy to miss and invisible on mobile) to a banner in the main content area. Clicking the banner opens a modal that lets users set their email directly without navigating away from the current page.

- Fixes #1108 
- Closes #2519 

## How Has This Been Tested?

- Dev server actively checking all the changes live

## Screenshots / Logs (if applicable)
- Local login (placeholder and hint)
image

- Password settings page:
image

- Warning when importing users
image

- Warning when disabling Media Server login in Settings > Users
image

- Local login invalid credentials
image

- User warning when require email is checked in settings > notifications > email:
image

- Popup for entering email address:
image

## Checklist:

- [X] I have read and followed the contribution [guidelines](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md).
- [ ] Disclosed any use of AI (see our [policy](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md#ai-assistance-notice))
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] Successful build `pnpm build`
- [X] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

## Summary by CodeRabbit

* **New Features**
  * Profile incomplete warning is now shown inline above content with a quick-action button that opens an Add Email modal; saving email validates and shows success/error toasts and refreshes profile data.
  * Login now distinguishes credential errors and shows Jellyfin/Emby username guidance when applicable.
  * Import flows now warn that imported users may lack passwords (Jellyfin/Emby/Plex).

* **Documentation**
  * Clarified password/setup copy and added new localized strings for these flows.

### CODE REVIEW

File: src/components/Login/LocalLogin.tsx [hunk 1]
```diff
@@ -18,7 +19,10 @@ const messages = defineMessages('components.Login', {
   password: 'Password',
   validationemailrequired: 'You must provide a valid email address',
   validationpasswordrequired: 'You must provide a password',
+  jellyfinLocalLoginHint:
+    "If you haven't set an email address in your profile, use your {mediaServerName} username instead.",
   loginerror: 'Something went wrong while trying to sign in.',
+  credentialerror: 'The email address or password is incorrect.',
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply src/components/Login/LocalLogin.tsx:25]: The local login field label is "Email Address" and the backend authenticates against `user.email`. For Jellyfin/Emby users whose email happens to be set to their username, there's already a contextual hint below the field explaining this. The error message should match the field label, not the hint. Keeping it as "email address or password" is correct here.

**Review by gauthier-th — APPROVED** [review]
Nice enhancement

File: src/components/Login/LocalLogin.tsx [hunk 2]
```diff
@@ -107,6 +115,20 @@ const LocalLogin = ({ revalidate }: LocalLoginProps) => {
                     typeof errors.email === 'string' && (
                       <div className="error">{errors.email}</div>
                     )}
+                  {(settings.currentSettings.mediaServerType ===
```
Comment (michaelhthomas) [inline src/components/Login/LocalLogin.tsx:118]: Is there any way this message could be displayed only if this is actually a possible concern (i.e. only if there are users that don't have an email set)?

Comment (fallenbagel) [reply src/components/Login/LocalLogin.tsx:118]: We will have to query the db for all users and check if the email is valid or not

Comment (michaelhthomas) [reply src/components/Login/LocalLogin.tsx:118]: Yeah, good point, it might not be worth the tradeoff there. Just thought it might be a bit cleaner.

Comment (fallenbagel) [reply src/components/Login/LocalLogin.tsx:118]: > Yeah, good point, it might not be worth the tradeoff there. Just thought it might be a bit cleaner.

I also thought of doing that. But that just creates extra latency/performance overhead just for a hint helper text 😔

**Review by M0NsTeRRR — APPROVED** [review]
