### PR TITLE
revert: reverts csrf-csrf back to csurf

### LINKED ISSUE #1441: Invalid CSRF Token
### Description

I run jellyseerr as a docker container behind traefik reverse proxy with SSL. Since updating to 2.4.0, the app is inaccessible with the error `{ "message": "invalid csrf token" }`.

Rolling back to 2.3.0, or disabling CSRF protection, resolves the issue.

### Version

2.4.0

### Steps to Reproduce

See above

### Screenshots

_No response_

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

Any

### Operating System

Any

### Browser

Any

### Additional Context

_No response_

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by fallenbagel**
#### Description
This reverts csrf-csrf change brought on by [9e3119](https://github.com/fallenbagel/jellyseerr/pull/1393/commits/9e3119850dac9d772de8a0a5a9377433d892de83) in #1393 back to `csurf` that is [maintained](https://www.npmjs.com/package/@dr.pogodin/csurf)

can be tested with `preview-csrf-protection-fix`

#### To-Dos

- [x] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #1441

### CODE REVIEW

**Review by gauthier-th — APPROVED** [review]

File: server/index.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ import restartFlag from '@server/utils/restartFlag';
 import { getClientIp } from '@supercharge/request-ip';
 import { TypeormStore } from 'connect-typeorm/out';
 import cookieParser from 'cookie-parser';
-import { doubleCsrf } from 'csrf-csrf';
+import csurf from 'csurf';
```
Comment (gauthier-th) [inline server/index.ts]:
```suggestion
import csurf from '@dr.pogodin/csurf';
```

**Review by gauthier-th — CHANGES_REQUESTED** [review]

**Review by gauthier-th — APPROVED** [review]
