### PR TITLE
fix(media): update delete media file logic to include is4k parameter

### LINKED ISSUE #1144: Using "Remove request from Sonarr" removes all show requests from all sonar instances
### Description

Often, I first request a series in 4K, and if that cannot be fulfilled, I then request it again in full HD (two distinct Sonarr instances). After that, I no longer want the 4K request to hang around pointlessly, so I go to requests and press "Remove from Sonarr." Since 4K Sonarr is recommended as a separate instance, I expect the requests will only be removed from the corresponding Sonarr instance. What happens is that all the show requests are removed from Jellyseerr regardless of the Sonarr instance used.

### Version

2.1.0

### Steps to Reproduce

1. Go to any TV series page
2. Request a season
3. Request a season in 4K
4. Go to requests page
5. Click remove from Sonarr of 4K request

### Screenshots

image

### Logs

_No response_

### Platform

desktop

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by 0xSysR3ll**
#### Description

When removing a 4K request from Sonarr or Radarr, it was accidentally removing all related requests - even the regular instance ones.

This PR fixes that by adding an `is4k` flag, so only the correct instance (4K or not) is affected when removing a request.

#### To-Dos

- [x] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #1144

### CODE REVIEW

File: server/routes/media.ts [hunk 1]
```diff
@@ -189,16 +189,18 @@ mediaRoutes.delete(
 
 mediaRoutes.delete(
   '/:id/file',
-  isAuthenticated(Permission.MANAGE_REQUESTS),
+  isAuthenticated(Permission.ADMIN),
```
Comment (gauthier-th) [inline server/routes/media.ts]: Why? The "Remove from *arr" button is also available to users with the MANAGE_REQUEST permission

**Review by gauthier-th — CHANGES_REQUESTED** [review]

File: server/routes/media.ts (hunk 1 above)
Comment (0xSysR3ll) [reply server/routes/media.ts]: Well, my bad — I assumed the button was admin-only.

**Review by gauthier-th — APPROVED** [review]

**Comment by Panda260** [comment]
@0xSysR3ll I’m on the latest release, and when I request both 1080p and 4K, everything works fine all background jobs run in the background over a few hours. But when I click Remove 4K, all requests, tags, and user data are deleted from the movie and the movie is even removed from the 1080p instance, even though I only clicked to remove it from the 4K instance.

**Comment by 0xSysR3ll** [comment]
> @0xSysR3ll I’m on the latest release, and when I request both 1080p and 4K, everything works fine all background jobs run in the background over a few hours. But when I click Remove 4K, all requests, tags, and user data are deleted from the movie and the movie is even removed from the 1080p instance, even though I only clicked to remove it from the 4K instance.

Sorry about that. I’ll need to investigate further — I’m not sure why it worked during my tests.

**Comment by Panda260** [comment]
👍
