### PR TITLE
fix(servarr): replace spaces in arr user tags with `-`

### LINKED ISSUE #1897: `Tag Requests` should not contain spaces per Sonarr and Radarr specifications
### Description

The Sonarr and Radarr APIs currently allow tags with spaces; however, as discussed in https://github.com/Sonarr/Sonarr/issues/7796, this behavior is not intended—tags are not supposed to contain spaces. This is consistent with the UI behavior of both applications, which validates and prevents the creation of tags with spaces.

Other tools, such as Bazarr, adhere to this specification and also disallow spaces in tags (see https://github.com/morpheus65535/bazarr/issues/3024).

To maintain compatibility across tools, tags created when the `Tag Requests` option is enabled should also avoid using spaces. Including spaces in tags makes it impossible to build reliable automations with applications that enforce the no-space restriction.

### Version

2.7.3

### Steps to Reproduce

1. Go to `Settings`.
2. Navigate to the `Services` tab.
3. Click on `Edit` for a Sonarr or Radarr instance.
4. Enable `Tag Requests`.
5. Request something.
6. See how the tag contains spaces in Sonarr/Radar.

### Screenshots

_No response_

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

MacBook Pro

### Operating System

macOS

### Browser

Firefox

### Additional Context

If you try to create a tag with spaces in Sonarr or Radarr's UI, it will be rejected. The interface does not allow tags containing spaces.

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

### LINKED ISSUE #2229: `Tag Requests` usernames are not sanitized when attempting to tag requests
### Description

Radarr enforces `[-0-9a-z]` as the only valid characters for a tag (and presumably Sonarr will follow suit?) and rejects calls where the tag label does not satisfy that constraint.

#1897 changed the Seerr request to remove the spaces that Seerr was inserting, however usernames can still violate the constraint and need to be sanitized. Issue is not resolved.

### Version

15356dfe496aef3ef6e6cf37b9fd359d1201a984

### Steps to Reproduce

1. Have a username with one-or-more invalid character(s), e.g. `user.name` or `user_name` or `user name`.
2. Make a request for a movie using Seerr to a Radarr instance configured to tag requests with user ID and name
3. Review logs for failure notification due to invalid characters.

### Screenshots

_No response_

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

N/A

### Operating System

N/A

### Browser

N/A

### Additional Context

_No response_

### Code of Conduct

- [x] I agree to follow Seerr's Code of Conduct

### PR DESCRIPTION
**Pull request by fallenbagel**
## Description
This PR updates the tag sanitization logic for arr tags to properly handle disallowed characters:
- Normalizes diacritics (e.g., é → e)
- Replaces spaces with hyphens
- Strips any non-alphanumeric characters (except hyphens)

> [!WARNING]
> If you are running develop and have already ran the migration 0007_migrate_arr_tags, you will  need to remove 0007_migrate_arr_tags from the migrations array in your settings.json file for the updated migration to run again.

- Fixes #2229 
- Fixes #1897

## Checklist:

- [X] I have read and followed the contribution [guidelines](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md).
- [ ] Disclosed any use of AI (see our [policy](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md#ai-assistance-notice))
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

### CODE REVIEW

**Review by 0xSysR3ll — DISMISSED** [review]

File: server/lib/settings/migrations/0008_migrate_arr_tags_remove_spaces.ts
Comment (gauthier-th) [inline server/lib/settings/migrations/0008_migrate_arr_tags_remove_spaces.ts:1]: Do you really think a new migration is necessary? The previous one (0007) does already the exact same job.
I think we can still add this extra check on that previous one without having to worry about it, since it's a very niche feature, and the previous migration has not been released yet.

File: server/subscriber/MediaRequestSubscriber.ts [hunk 1]
```diff
@@ -313,8 +313,11 @@ export class MediaRequestSubscriber
                 entity.requestedBy.id + '-' + entity.requestedBy.displayName,
             });
             userTag = await radarr.createTag({
-              label:
-                entity.requestedBy.id + '-' + entity.requestedBy.displayName,
+              label: (
+                entity.requestedBy.id +
+                '-' +
+                entity.requestedBy.displayName
+              ).replace(/\s+/g, '-'),
```
Comment (gauthier-th) [inline server/subscriber/MediaRequestSubscriber.ts]: IMHO make more sense to replace only on the `displayName` (no space in `id` or `'-'`), but that's up to you.

File: server/subscriber/MediaRequestSubscriber.ts [hunk 2]
```diff
@@ -634,8 +637,11 @@ export class MediaRequestSubscriber
                 entity.requestedBy.id + '-' + entity.requestedBy.displayName,
             });
             userTag = await sonarr.createTag({
-              label:
-                entity.requestedBy.id + '-' + entity.requestedBy.displayName,
+              label: (
+                entity.requestedBy.id +
+                '-' +
+                entity.requestedBy.displayName
+              ).replace(/\s+/g, '-'),
```
Comment (gauthier-th) [inline server/subscriber/MediaRequestSubscriber.ts]: Same here

File: server/lib/settings/migrations/0008_migrate_arr_tags_remove_spaces.ts
Comment (fallenbagel) [reply server/lib/settings/migrations/0008_migrate_arr_tags_remove_spaces.ts:1]: But a lot of people have already ran develop. And the 007 will be skipped for them. It will be a support burden to explain to each and everyone to remove it

Comment (gauthier-th) [reply server/lib/settings/migrations/0008_migrate_arr_tags_remove_spaces.ts:1]: `develop` is not stable, that's the point of the branch. Adding this to the existing migration will only cause issues for a very tiny amount of users. I don't think there is more than a few users running `develop` AND having an user with a space in the username.
IMO it's fine to go this way to avoid all this extra code that can easily be avoided.

**Comment by v3DJG6GL** [comment]
thanks for this PR!

I am still getting this error on _Radarr v6_
```
2025-12-15 17:01:26.4|Debug|Api|[GET] /api/v3/tag?apikey=(removed) 200.OK (1 ms)
2025-12-15 17:01:26.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Label: Allowed characters a-z, 0-9 and -
2025-12-15 17:01:26.4|Debug|Api|[PUT] /api/v3/tag/22?apikey=(removed) 400.BadRequest (3 ms)
```
Seerr logs:

```
2025-12-15T16:01:26.370Z [debug][Settings Migrator]: Checking migration '0001_migrate_hostname.js'... 
2025-12-15T16:01:26.372Z [debug][Settings Migrator]: Checking migration '0002_migrate_apitokens.js'... 
2025-12-15T16:01:26.374Z [debug][Settings Migrator]: Checking migration '0003_emby_media_server_type.js'... 
2025-12-15T16:01:26.375Z [debug][Settings Migrator]: Checking migration '0004_migrate_region_setting.js'... 
2025-12-15T16:01:26.376Z [debug][Settings Migrator]: Checking migration '0005_migrate_network_settings.js'... 
2025-12-15T16:01:26.377Z [debug][Settings Migrator]: Checking migration '0006_remove_lunasea.js'... 
2025-12-15T16:01:26.378Z [debug][Settings Migrator]: Checking migration '0007_migrate_arr_tags.js'... 
Unable to rename Radarr tags to the new format. Please check your Radarr connection settings for the instance "Radarr". [Radarr] Failed to rename tag: Request failed with status code 400
2025-12-15T16:01:26.443Z [debug][Settings Migrator]: Checking migration '0008_migrate_arr_tags_remove_spaces.js'... 
2025-12-15T16:01:26.447Z [info][DNS Cache]: Initializing DNS Cache 
2025-12-15T16:01:26.449Z [info][Notifications]: Registered notification agents 
2025-12-15T16:01:26.493Z [info][Jobs]: Scheduled jobs loaded 
2025-12-15T16:01:26.655Z [info][Server]: Server ready on port 5055 
2025-12-15T16:02:00.006Z [debug][Jobs]: Starting scheduled job: Download Sync 
```


But idk if the rename error comes from `0007_migrate_arr_tags.js` or from `0008_migrate_arr_tags_remove_spaces.js`...

Nevertheless, tags in radarr are still not renamed, while in sonarr they are now renamed from
```
12 - noam meyer
```
to
```
12-noam-meyer
```
I suppose the issue is related to user names that contain umlauts - which is very common in german speaking countries. radarr v6 permits tags with umlauts like e.g.
```
12-noam-müller
```
in such situations umlauts are generally transcribed/transliterated as follows:
`ä` --> `ae`
`ö` --> `oe`
`ü` --> `ue`

The same goes for the `sharp S` _(although i don't think it's occurs often in names/surnames)_
`ß` --> `ss`

_EDIT: (with a little help of AI)_
- French/Portuguese special characters:
`à` --> `a`
`â` --> `a`
`ç` --> `c`
`é` --> `e`
`è` --> `e`
`ê` --> `e`
`î` --> `i`
`ô` --> `o`
`ù` --> `u`
`û` --> `u`

- French-specific special characters:
`ë` --> `e`
`ï` --> `i`
`ÿ` --> `y`
`æ` --> `ae`
`œ` --> `oe`

- Portuguese-specific special characters:
`ã` --> `a`
`õ` --> `o`

**Comment by gauthier-th** [comment]
@fallenbagel if you agree with what I said earlier, this PR should be changed to "replace disallowed characters in arr tags", remove the 0008 migration, and update the previous one with something like this ([source](https://stackoverflow.com/a/37511463)):
```js
displayName.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[a-z0-9-]/i, "")
```

**Comment by fallenbagel** [comment]
> @fallenbagel if you agree with what I said earlier

I thought I already said yes 😛

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts [hunk 3]
```diff
@@ -30,15 +30,24 @@ const migrationArrTags = async (settings: any): Promise<AllSettings> => {
...
           id: userTag.id,
-          label: userTag.label.replace(`${user.id} - `, `${user.id}-`),
+          label:
+            user.id +
+            '-' +
+            user.displayName
+              .normalize('NFD')
+              .replace(/[\u0300-\u036f]/g, '')
+              .replace(/\s+/g, '-')
+              .replace(/[^a-z0-9-]/gi, ''),
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts]: I dont think this is worth the change? @gauthier-th wdyt?

Like realistically, how many users have display names like " John " or "John @#$ Doe" anyways.

[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts]: @gauthier-th wb for this. I was originally gonna extract it into a util function but then again the original one also had it inlined and the only reason the references are more is because of the migration script which will be a one time thing anyways. Wdyt?

File: server/subscriber/MediaRequestSubscriber.ts [hunk 4]
```diff
@@ -310,11 +310,23 @@ export class MediaRequestSubscriber
...
               userId: entity.requestedBy.id,
               newTag:
-                entity.requestedBy.id + '-' + entity.requestedBy.displayName,
+                entity.requestedBy.id +
+                '-' +
+                entity.requestedBy.displayName
+                  .normalize('NFD')
+                  .replace(/[\u0300-\u036f]/g, '')
+                  .replace(/\s+/g, '-')
+                  .replace(/[^a-z0-9-]/gi, ''),
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/subscriber/MediaRequestSubscriber.ts]: Same as above

[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/subscriber/MediaRequestSubscriber.ts]: Same as below

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (gauthier-th) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts]: That's a bit verbose but I guess it's fine. Or maybe just a helper function in `MediaRequestSubscriber.ts` to remove the 4 occurences?

[the remark this answers is not in the document]
Comment (gauthier-th) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts]: It may not be worth much, but it's just a small effort, just in case?

**Review by gauthier-th — DISMISSED** [review]
LGTM

**Review by 0xSysR3ll — DISMISSED** [review]

**Comment by v3DJG6GL** [comment]
I get this error with the latest commits:
```
2025-12-18T16:41:02.055Z [debug][Settings Migrator]: Checking migration '0007_migrate_arr_tags.js'... 
Unable to rename Radarr tags to the new format. Please check your Radarr connection settings for the instance "Radarr". Cannot read properties of undefined (reading 'normalize')
Unable to rename Sonarr tags to the new format. Please check your Sonarr connection settings for the instance "Sonarr". Cannot read properties of undefined (reading 'normalize')
```
_Note: I forked seerr to integrate both QuickConnect+OIDC + this PR - everything else is based in Seerr develop branch:_
https://github.com/v3DJG6GL/seerr/tree/feat-OIDC%2BJellyfin-QuickConnect

**Comment by fallenbagel** [comment]
> I get this error with the latest commits:
> 
> ```
> 2025-12-18T16:41:02.055Z [debug][Settings Migrator]: Checking migration '0007_migrate_arr_tags.js'... 
> Unable to rename Radarr tags to the new format. Please check your Radarr connection settings for the instance "Radarr". Cannot read properties of undefined (reading 'normalize')
> Unable to rename Sonarr tags to the new format. Please check your Sonarr connection settings for the instance "Sonarr". Cannot read properties of undefined (reading 'normalize')
> ```
> 
> _Note: I forked seerr to integrate both QuickConnect+OIDC + this PR - everything else is based in Seerr develop branch:_ https://github.com/v3DJG6GL/seerr/tree/feat-OIDC%2BJellyfin-QuickConnect

Yeah my bad. I missed `displayName` select. It should work now.

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts [hunk 5]
```diff
@@ -14,7 +14,7 @@ const migrationArrTags = async (settings: any): Promise<AllSettings> => {
 
   const userRepository = getRepository(User);
   const users = await userRepository.find({
-    select: ['id'],
+    select: ['id', 'displayName'],
```
Comment (v3DJG6GL) [inline server/lib/settings/migrations/0007_migrate_arr_tags.ts]:
```suggestion
    select: ['id', 'username'],
```

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts [hunk 6]
```diff
@@ -30,15 +30,26 @@ const migrationArrTags = async (settings: any): Promise<AllSettings> => {
...
         if (!userTag) {
           continue;
         }
         await radarr.renameTag({
           id: userTag.id,
-          label: userTag.label.replace(`${user.id} - `, `${user.id}-`),
+          label:
+            user.id +
+            '-' +
+            user.displayName
```
Comment (v3DJG6GL) [inline server/lib/settings/migrations/0007_migrate_arr_tags.ts:44]:
```suggestion
            user.username
```

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts [hunk 7]
```diff
@@ -61,15 +72,26 @@ const migrationArrTags = async (settings: any): Promise<AllSettings> => {
...
         if (!userTag) {
           continue;
         }
         await sonarr.renameTag({
           id: userTag.id,
-          label: userTag.label.replace(`${user.id} - `, `${user.id}-`),
+          label:
+            user.id +
+            '-' +
+            user.displayName
```
Comment (v3DJG6GL) [inline server/lib/settings/migrations/0007_migrate_arr_tags.ts:86]:
```suggestion
            user.username
```

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts [hunk 8]
```diff
@@ -30,15 +30,26 @@ const migrationArrTags = async (settings: any): Promise<AllSettings> => {
       });
       const radarrTags = await radarr.getTags();
       for (const user of users) {
-        const userTag = radarrTags.find((v) =>
-          v.label.startsWith(user.id + ' - ')
+        const userTag = radarrTags.find(
```
Comment (v3DJG6GL) [inline server/lib/settings/migrations/0007_migrate_arr_tags.ts:31]:
```suggestion
        if (!user.username) {
          continue;
        }
        const userTag = radarrTags.find(
```

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts [hunk 9]
```diff
@@ -61,15 +72,26 @@ const migrationArrTags = async (settings: any): Promise<AllSettings> => {
       });
       const sonarrTags = await sonarr.getTags();
       for (const user of users) {
-        const userTag = sonarrTags.find((v) =>
-          v.label.startsWith(user.id + ' - ')
+        const userTag = sonarrTags.find(
```
Comment (v3DJG6GL) [inline server/lib/settings/migrations/0007_migrate_arr_tags.ts:73]:
```suggestion
        if (!user.username) {
          continue;
        }
        const userTag = sonarrTags.find(
```

**Review by v3DJG6GL — COMMENTED** [review]
hmh, with these changes seerr was not even starting at my end:
```
2025-12-18T23:21:37.935Z [error][Settings Migrator]: Error while running migration '0007_migrate_arr_tags.js': Property "displayName" was not found in "User". Make sure your query is correct.
EntityPropertyNotFoundError: Property "displayName" was not found in "User". Make sure your query is correct.
    at SelectQueryBuilder.buildSelect (/app/node_modules/.pnpm/typeorm@0.3.12_pg@8.16.3_sqlite3@5.1.7_ts-node@10.9.2_@swc+core@1.6.5_@swc+helpers@0.5._51f434fa4dcd4620f1c02c412e887ce2/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2210:23)
    at SelectQueryBuilder.applyFindOptions (/app/node_modules/.pnpm/typeorm@0.3.12_pg@8.16.3_sqlite3@5.1.7_ts-node@10.9.2_@swc+core@1.6.5_@swc+helpers@0.5._51f434fa4dcd4620f1c02c412e887ce2/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1731:22)
    at SelectQueryBuilder.setFindOptions (/app/node_modules/.pnpm/typeorm@0.3.12_pg@8.16.3_sqlite3@5.1.7_ts-node@10.9.2_@swc+core@1.6.5_@swc+helpers@0.5._51f434fa4dcd4620f1c02c412e887ce2/node_modules/typeorm/query-builder/SelectQueryBuilder.js:69:14)
    at EntityManager.find (/app/node_modules/.pnpm/typeorm@0.3.12_pg@8.16.3_sqlite3@5.1.7_ts-node@10.9.2_@swc+core@1.6.5_@swc+helpers@0.5._51f434fa4dcd4620f1c02c412e887ce2/node_modules/typeorm/entity-manager/EntityManager.js:521:14)
    at Repository.find (/app/node_modules/.pnpm/typeorm@0.3.12_pg@8.16.3_sqlite3@5.1.7_ts-node@10.9.2_@swc+core@1.6.5_@swc+helpers@0.5._51f434fa4dcd4620f1c02c412e887ce2/node_modules/typeorm/repository/Repository.js:197:29)
    at migrationArrTags (/app/dist/lib/settings/migrations/0007_migrate_arr_tags.js:16:40)
    at runMigrations (/app/dist/lib/settings/migrator.js:56:43)
    at async Settings.load (/app/dist/lib/settings/index.js:426:34)
    at async /app/dist/index.js:100:22 
2025-12-18T23:21:37.935Z [error][Settings Migrator]: A common cause for this error is a permission issue with your configuration folder, a network issue or a corrupted database. 
```
are there some DB changes I missed?

I therefore made some changes to `0007_migrate_arr_tags`. Now seerr is starting at my end and tags were correctly migrated :)

File: server/subscriber/MediaRequestSubscriber.ts [hunk 10]
```diff
@@ -29,6 +29,16 @@ import type {
...
 import { EventSubscriber } from 'typeorm';
 
+const sanitizeDisplayName = (displayName: string): string => {
+  return displayName
+    .normalize('NFD')
+    .replace(/[\u0300-\u036f]/g, '')
+    .replace(/\s+/g, '-')
+    .replace(/[^a-z0-9-]/gi, '')
+    .replace(/-+/g, '-')
+    .replace(/^-|-$/g, '');
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/subscriber/MediaRequestSubscriber.ts:39]: Not relevant

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts [hunk 11]
```diff
@@ -30,15 +30,26 @@ const migrationArrTags = async (settings: any): Promise<AllSettings> => {
       });
       const radarrTags = await radarr.getTags();
       for (const user of users) {
-        const userTag = radarrTags.find((v) =>
-          v.label.startsWith(user.id + ' - ')
+        const userTag = radarrTags.find(
+          (v) =>
+            v.label.startsWith(user.id + ' - ') ||
+            v.label.startsWith(user.id + '-')
         );
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts:35]: This should be fine. Multiple tags wouldn't exist for a single user

[the remark this answers is not in the document]
Comment (gauthier-th) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts:35]: Agree

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts (hunk 5 above)
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts]: We should be using `displayName` not username like how its done on `mediaRequestSubscriber` and has been done previously as well. I forgot that it was populated by the `@AfterLoad()` hook. So we need to load the entire user entity.

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts (hunk 8 above)
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts:31]: Same as above

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts (hunk 6 above)
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts:44]: Same as above

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts (hunk 9 above)
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts:73]: Same as above

File: server/lib/settings/migrations/0007_migrate_arr_tags.ts (hunk 7 above)
Comment (fallenbagel) [reply server/lib/settings/migrations/0007_migrate_arr_tags.ts:86]: Same as above

**Comment by fallenbagel** [comment]
> I therefore made some changes to `0007_migrate_arr_tags`.

I just pushed the proper fix. We should be using `displayName` and not `username`.

**Comment by fallenbagel** [comment]
@0xSysR3ll @gauthier-th Should be ready for reviewing and testing now

**Review by gauthier-th — APPROVED** [review]
