### PR TITLE
fix(proxy): configure proxy agent connection limits and IPv4 support

### LINKED ISSUE #2297: HTTP connection leak to Sonarr/Radarr causes downstream service deadlock
### Description

 Seerr accumulates HTTP keep-alive connections to Sonarr/Radarr over time. After 1-2 weeks of uptime, 100-200+ stale connections accumulate, eventually causing Sonarr/Radarr to become unresponsive due to .NET thread pool exhaustion.

The root cause is in `server/api/externalapi.ts` - the axios instance is created without HTTP agent configuration, using Node.js's global agent with `maxSockets: Infinity` and no idle timeout.

### Version

2.7.3

### Steps to Reproduce

  1. Run Seerr connected to Sonarr/Radarr
  2. Leave running for 1-2 weeks
  3. Monitor connections: `ss -tnp dport = :8989 | wc -l`
  4. Observe connection count grows continuously (100-200+)
  5. Eventually Sonarr API becomes unresponsive

### Screenshots

_No response_

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

Linux Server

### Operating System

NixOS 25.11

### Browser

N/A

### Additional Context

 Proposed fix - configure HTTP agents in `server/api/externalapi.ts`:

  ```typescript
  const httpAgent = new http.Agent({
    keepAlive: true,
    maxSockets: 10,
    keepAliveMsecs: 30000,
  });

  this.axios = axios.create({
    baseURL: baseUrl,
    httpAgent,
    httpsAgent,
    timeout: 30000,
    ...
  });


### Search Existing Issues

- [x] Yes, I have searched existing issues.

### Code of Conduct

- [x] I agree to follow Seerr's Code of Conduct

### PR DESCRIPTION
**Pull request by fallenbagel**
## Description

Configures axios and undici proxy agents with connection pool limits and idle timeouts to prevent connection accumulation. The undici agents already had `keepAliveTimeout: 5000` configured, but we're missing connection limits and axios was using Node's default agent with unlimited sockets and no idle timeout. This caused connections to accumulate over time. 

This PR adds `maxSockets` and `maxFreeSockets` to bound the connection pool, a matching 5 second idle `timeout`, and LIFO scheduling to naturally cycle out older connections. `connections` limit of 50 were also added to undici agents (defaultAgent and ProxyAgent). In addition, it also passes the `forceIpv4First` setting to the proxy agent which previously overwrote that option, breaking the IPV4-first resolution when both proxy and `forceIpv4First were enabled.

- Fixes #2297

## How Has This Been Tested?

(no need tbh).

## Checklist:

- [X] I have read and followed the contribution [guidelines](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md).
- [ ] Disclosed any use of AI (see our [policy](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md#ai-assistance-notice))
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

### CODE REVIEW

File: server/utils/customProxyAgent.ts [hunk 1]
```diff
@@ -11,7 +11,8 @@ export let requestInterceptorFunction: (
 ) => InternalAxiosRequestConfig;
 
 export default async function createCustomProxyAgent(
-  proxySettings: ProxySettings
+  proxySettings: ProxySettings,
+  forceIpv4First?: boolean
 ) {
   const defaultAgent = new Agent({ keepAliveTimeout: 5000 });
```
Comment (gauthier-th) [inline server/utils/customProxyAgent.ts]: Maybe you could also add the same parameters for Undici here?

Comment (fallenbagel) [reply server/utils/customProxyAgent.ts]: Good idea. Better to be consistent

**Comment by fallenbagel** [comment]
> LGTM. We should probably create a preview tag to test this before merging?

Preview deployed

**Comment by gauthier-th** [comment]
Fix confirmed working.

**Review by 0xSysR3ll — APPROVED** [review]
