### PR TITLE
fix: add email requirement for local users

### LINKED ISSUE #1367: Local User Request Limit Override Not Persisting
### Description

When attempting to set a request limit override on a Local User in JellySeerr, the change does not persist after saving. However, performing the same action on a Jellyfin user works as expected.

### Version

2.3.0

### Steps to Reproduce

1. Go to Users in JellySeerr.
2. Select a Local User.
3. Set a request limit override and save.
4. Refresh the page or navigate away and return.
5. Observe that the override has not persisted.

### Screenshots

Pre-Save
Image
After-Save
Image

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

PC

### Operating System

Windows 11

### Browser

Firefox

### Additional Context

_No response_

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by gauthier-th**
#### Description

Because of a misunderstanding, the requirement to have a mandatory email for local users was removed, when it shouldn't have been.

#### To-Dos

- [x] Successful build `pnpm build`
- [x] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Related to #900
- Fixes #1367

### CODE REVIEW

File: src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx [hunk 1]
```diff
@@ -100,7 +100,8 @@ const UserGeneralSettings = () => {
 
   const UserGeneralSettingsSchema = Yup.object().shape({
     email:
-      user?.id === 1
+      // email is required for everybody except non-admin jellyfin users
+      user?.id === 1 || user?.userType !== UserType.JELLYFIN
```
Comment (fallenbagel) [inline src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx]: UseType might be emby too right?

Comment (gauthier-th) [reply src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx]: Oh yeah my bad

**Review by fallenbagel — APPROVED** [review]
