### PR TITLE
fix(csrf): override fetch to handle requests with CSRF token

### LINKED ISSUE #1011: [Bug] CSRF Validation broken since 2.0.0
### Description

i Have CSRF Protection enabled and my Jellyseerr behind reverse proxy, after upgrading to 2.0.0 every request fails with 

`{
    "message": "invalid csrf token"
}`

and the http status code 403, this only started happening after upgrading to 2.0.0

### Version

2.0.0

### Steps to Reproduce

1. Enable CSRF-Protection
2. Make sure you have version 2.0.0 running
3. Try to request anything or save the settings

### Screenshots

_No response_

### Logs

_No response_

### Platform

desktop

### Device

Windows

### Operating System

Windows 11

### Browser

Chrome

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by Fallenbagel**
#### Description
During the migration from Axios to fetch, we overlooked the fact that Axios automatically handled CSRF tokens, while fetch does not. When CSRF protection was turned on, requests were failing with an
"invalid CSRF token" error for users accessing the app even via HTTPS. This PR overrides fetch to ensure that the CSRF token is included in all requests.

@M0NsTeRRR thanks for helping me debug and find a solution!

#### To-Dos

- [ ] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

#### Issues Fixed or Closed

- Fixes #1011

### CODE REVIEW

**Comment by Fallenbagel** [comment]
@all-contributors please add @M0NsTeRRR for security

File: src/utils/apiFetch.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+  url: string,
+  options?: RequestInit
+): Promise<Response> => {
+  const csrfToken = getCsrfToken();
+
+  const updatedOptions: RequestInit = {
+    ...options,
+    headers: {
+      ...options?.headers,
+      'X-XSRF-TOKEN': csrfToken,
```
Comment (fallenbagel) [inline src/utils/apiFetch.ts]: @M0NsTeRRR should I rename this to `XSRF-TOKEN`?

Comment (M0NsTeRRR) [reply src/utils/apiFetch.ts]: Yes as stated by [rfc6648](https://datatracker.ietf.org/doc/html/rfc6648) and csurf supports it https://www.npmjs.com/package/csurf#value

File: src/components/Login/JellyfinLogin.tsx [hunk 2]
```diff
@@ -114,8 +115,9 @@ const JellyfinLogin: React.FC<JellyfinLoginProps> = ({
             //   throw new Error('Invalid serverType'); // You can customize the error message
             // }
 
-            const res = await fetch('/api/v1/auth/jellyfin', {
+            const res = await apiFetch('/api/v1/auth/jellyfin', {
               method: 'POST',
+              credentials: 'same-origin',
```
Comment (M0NsTeRRR) [inline src/components/Login/JellyfinLogin.tsx]: You forgot to remove it (still not an issue ofc)

Comment (fallenbagel) [reply src/components/Login/JellyfinLogin.tsx]: Let me remove it

**Review by gauthier-th — APPROVED** [review]
lgtm
