### PR TITLE
fix: preserve blocklist on media deletion & optimise watchlist-sync

### LINKED ISSUE #2475: Media from watchlist with auto-approve isn't respected in blocklist
### Description

I just migrated from overseerr to seerr and the blocklist doesnt appear to be working how I expected. If I have a user whose requests are auto-approved and auto-request is on their watchlist, a request is still placed despite being on a blocklist. This behavior happens across multiple users and media types (tv & movies) 

### Version

3.0.1

### Steps to Reproduce

Set user to auto-request via watchlist
Set user permissions to auto-approve
Wait for media to fetch (working as expected)
Blocklist media
Delete from *arr, via Seerr interface
Retrigger watchlist sync. 
Request is placed for blocklisted content (bug?)

### Screenshots

Image
Image
Image

### Logs

```shell
2026-02-17T08:30:00.027Z [info][Jobs]: Starting scheduled job: Plex Watchlist Sync 
2026-02-17T08:30:00.689Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":12,"mediaTitle":"Severance"}
2026-02-17T08:30:00.692Z [debug][Watchlist Sync]: Failed to create media request from watchlist {"userId":12,"mediaTitle":"Severance","errorMessage":"Series Quota exceeded."}
2026-02-17T08:30:00.692Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":12,"mediaTitle":"The Increasingly Poor Decisions of Todd Margaret"}
2026-02-17T08:30:00.694Z [debug][Watchlist Sync]: Failed to create media request from watchlist {"userId":12,"mediaTitle":"The Increasingly Poor Decisions of Todd Margaret","errorMessage":"Series Quota exceeded."}
2026-02-17T08:30:02.738Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":16,"mediaTitle":"House of Guinness"}
2026-02-17T08:30:02.772Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_APPROVED {"subject":"House of Guinness (2025)"}
2026-02-17T08:30:02.772Z [debug][Notifications]: Sending webhook notification {"type":"MEDIA_AUTO_APPROVED","subject":"House of Guinness (2025)"}
2026-02-17T08:30:02.774Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_REQUESTED {"subject":"House of Guinness (2025)"}
2026-02-17T08:30:02.774Z [debug][Notifications]: Sending email notification {"recipient":"user1","type":"MEDIA_AUTO_REQUESTED","subject":"House of Guinness (2025)"}
2026-02-17T08:30:02.789Z [debug][Notifications]: Sending email notification {"recipient":"user2","type":"MEDIA_AUTO_APPROVED","subject":"House of Guinness (2025)"}
2026-02-17T08:30:02.797Z [info][Media Request]: Sent request to Sonarr {"requestId":546,"mediaId":655}
2026-02-17T08:30:02.821Z [debug][Notifications]: Sending web push notification {"recipient":"user2","type":"MEDIA_AUTO_APPROVED","subject":"House of Guinness (2025)"}
2026-02-17T08:30:02.830Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":16,"mediaTitle":"The Sopranos"}
2026-02-17T08:30:02.836Z [debug][Watchlist Sync]: Failed to create media request from watchlist {"userId":16,"mediaTitle":"The Sopranos","errorMessage":"Series Quota exceeded."}
2026-02-17T08:30:02.836Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":16,"mediaTitle":"A Clockwork Orange"}
2026-02-17T08:30:02.836Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":16,"mediaTitle":"City of God"}
2026-02-17T08:30:02.836Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":16,"mediaTitle":"The Ugly Stepsister"}
2026-02-17T08:30:02.837Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":16,"mediaTitle":"My Wife and Kids"}
2026-02-17T08:30:02.844Z [debug][Watchlist Sync]: Failed to create media request from watchlist {"userId":16,"mediaTitle":"My Wife and Kids","errorMessage":"Series Quota exceeded."}
2026-02-17T08:30:02.856Z [info][Sonarr]: Updated existing series in Sonarr. {"seriesId":172,"seriesTitle":"House of Guinness"}
2026-02-17T08:30:02.856Z [debug][Sonarr]: Sonarr update details {"series":{"title":"House of Guinness","alternateTitles":[],"sortTitle":"house of guinness","status":"continuing","ended":false,"overview":"Set in 19th-century Dublin and New York, the story focuses on the consequences of the death of Benjamin Guinness, the man responsible for the extraordinary success of the Guinness brewery, and the far-reaching impact of his cunning will on the fate of his four adult children, Arthur, Edward, Anne, and Ben, as well as on a group of Dublin characters who work and interact with the growing juggernaut that is Guinness.","previousAiring":"2025-09-25T08:00:00Z","network":"Netflix","airTime":"04:00","images":[{"coverType":"banner","url":"/MediaCover/172/banner.jpg?lastWrite=639069120043345708","remoteUrl":"https://artworks.thetvdb.com/banners/v4/series/447594/banners/68b886466576c.jpg"},{"coverType":"poster","url":"/MediaCover/172/poster.jpg?lastWrite=639069120043665709","remoteUrl":"https://artworks.thetvdb.com/banners/v4/series/447594/posters/6951981f7a50b.jpg"},{"coverType":"fanart","url":"/MediaCover/172/fanart.jpg?lastWrite=639069120043905711","remoteUrl":"https://artworks.thetvdb.com/banners/v4/series/447594/backgrounds/68e6f05fd36db.jpg"},{"coverType":"clearlogo","url":"/MediaCover/172/clearlogo.png?lastWrite=639069120043985711","remoteUrl":"https://artworks.thetvdb.com/banners/v4/series/447594/clearlogo/68d5184b37f60.png"}],"originalLanguage":{"id":1,"name":"English"},"seasons":[{"seasonNumber":1,"monitored":true,"statistics":{"previousAiring":"2025-09-25T08:00:00Z","episodeFileCount":0,"episodeCount":8,"totalEpisodeCount":8,"sizeOnDisk":0,"releaseGroups":[],"percentOfEpisodes":0}}],"year":2025,"path":"/tv/House of Guinness (2025) {tmdb-250988}","qualityProfileId":6,"seasonFolder":true,"monitored":true,"monitorNewItems":"all","useSceneNumbering":false,"runtime":51,"tvdbId":447594,"tvRageId":0,"tvMazeId":75496,"tmdbId":250988,"firstAired":"2025-09-25T00:00:00Z","lastAired":"2025-09-25T00:00:00Z","seriesType":"standard","cleanTitle":"houseguinness","imdbId":"tt13542714","titleSlug":"house-of-guinness","rootFolderPath":"/tv","certification":"16+","genres":["Drama","History"],"tags":[31,14],"added":"2026-02-17T08:00:04Z","ratings":{"votes":26725,"value":7.4},"statistics":{"seasonCount":1,"episodeFileCount":0,"episodeCount":8,"totalEpisodeCount":8,"sizeOnDisk":0,"releaseGroups":[],"percentOfEpisodes":0},"languageProfileId":1,"id":172}}
2026-02-17T08:30:02.862Z [info][Sonarr API]: Executing series search command. {"seriesId":172}
2026-02-17T08:31:00.016Z [debug][Jobs]: Starting scheduled job: Download Sync
```

### Platform

desktop

### Database

SQLite (default)

### Device

dell laptop

### Operating System

Debian 13

### Browser

chrome

### Additional Context

_No response_

### Search Existing Issues

- [x] Yes, I have searched existing issues.

### Code of Conduct

- [x] I agree to follow Seerr's Code of Conduct

### PR DESCRIPTION
**Pull request by fallenbagel**
## Description
When a user blocklists media and then removes it from Sonarr/Radarr via the Seerr interface, the Media entity and its associated Blocklist record were both destroyed due to the cascade delete on the relationship. On the next watchlist sync cycle, no record existed to check against, so a fresh request was created and auto-approved, completely bypassing the blocklist.

This PR fixes the media delete endpoint to detect blocklisted status and preserve the entity by nulling out service-related fields rather than removing the row entirely. It also improves the watchlist sync filtering to exclude blocklisted media as a safety net and to skip items where the user already has an existing auto-request, eliminating the repeated unnecessary api calls and database lookups that were happening every sync cycle just to throw a duplicate request error.

- Fixes #2475 

## Checklist:

- [X] I have read and followed the contribution [guidelines](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md).
- [ ] Disclosed any use of AI (see our [policy](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md#ai-assistance-notice))
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

## Release Notes

* **Bug Fixes**
  * Watchlist sync now excludes items the user has already auto-requested, reducing duplicate requests.
  * Deleting a blocklisted media item now preserves the record while clearing external/service identifiers instead of removing it.
  * Watchlist sync still respects user permissions and settings; existing error handling for request creation remains unchanged.

### CODE REVIEW

File: server/routes/media.ts [hunk 1]
```diff
@@ -174,7 +174,22 @@ mediaRoutes.delete(
...
+        media.externalServiceSlug = null;
+        media.externalServiceSlug4k = null;
+        media.ratingKey = null;
+        media.ratingKey4k = null;
+        media.jellyfinMediaId = null;
+        media.jellyfinMediaId4k = null;
+
+        await mediaRepository.save(media);
+      } else {
+        await mediaRepository.remove(media);
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/routes/media.ts:181]: Irrelevant. And stupid. If an admin manually changes the status away from `BLOCKLISTED`, that's an intentional un-blocklist. Cascade-deleting the orphaned Blocklist record on a subsequent delete is correct behavior in that case.

File: server/routes/media.ts [hunk 2]
```diff
@@ -174,7 +174,22 @@ mediaRoutes.delete(
...
+        media.serviceId = null;
+        media.serviceId4k = null;
+        media.externalServiceId = null;
+        media.externalServiceId4k = null;
+        media.externalServiceSlug = null;
+        media.externalServiceSlug4k = null;
+        media.ratingKey = null;
+        media.ratingKey4k = null;
+        media.jellyfinMediaId = null;
+        media.jellyfinMediaId4k = null;
```
Comment (gauthier-th) [inline server/routes/media.ts]: This feels a bit hardcoded. Don't we have another way of resetting values of the entity? Doing this seems to be a good way of having issues later when we'll add other fields to the entity.

Comment (gauthier-th) [reply server/routes/media.ts]: Or delete/recreate the entity with the blacklisted status instead?

Comment (fallenbagel) [reply server/routes/media.ts]: > Or delete/recreate the entity with the blacklisted status instead?

The delete/recreate approach won't work because, deleting the Media would kill the Blocklist row before you can recreate.

One thing i could try is dynamically handling non-nullable columns to survive, and nullable ones to get cleared. Wdyt?

```
  for (const column of mediaRepository.metadata.columns) {
    if (column.isNullable && !column.isPrimary) {
      updatePayload[column.propertyName] = null;
    }
  }
```
And then
```
  await mediaRepository.update
```

Comment (gauthier-th) [reply server/routes/media.ts]: Yep, looks like more future-proof.

Comment (fallenbagel) [reply server/routes/media.ts]: @gauthier-th  Actually i just realised that approach wont work:
Nulling all nullable columns also wipes `tvdbId`, `imdbId`, and `mediaAddedAt` which aren't service data but they're media metadata required to identify them. If an admin later un-blocklists the media, those identifiers would be gone. 

another approach would then be hardcoding these fields in the entity itself rather than the route. Like `resetServiceData()` method on the entity. Wdyt? Atleast then everything will be in one place and will be easier to remember to update

Comment (gauthier-th) [reply server/routes/media.ts]: Good point. I do prefer the `resetServiceData()` option since it keeps all the entity logic at the same place.

File: server/routes/media.ts [hunk 3]
```diff
@@ -174,7 +174,19 @@ mediaRoutes.delete(
         where: { id: Number(req.params.id) },
       });
 
-      await mediaRepository.remove(media);
+      if (media.status === MediaStatus.BLOCKLISTED) {
```
[the remark this answers is not in the document]
Comment (fallenbagel) [reply server/routes/media.ts:177]: Adding the check for specific statuses aren't necessary here as addToBlocklist adds both the statuses to the blocklist and there is no logic to blocklist a specific type of status. So irrelevant.

File: server/routes/media.ts (hunk 2 above)
Comment (fallenbagel) [reply server/routes/media.ts]: Updated
